name: Validate

on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
    branches: ["main"]

jobs:
  validate-hacs:
    name: HACS validatie
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: HACS Action
        uses: hacs/action@main
        with:
          category: integration

  validate-hassfest:
    name: Hassfest validatie
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Hassfest
        uses: home-assistant/actions/hassfest@master